version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "root"
    privileged: true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /Data/grafana_data:/Data/grafana_data
    networks:
      - loki
